language: erlang
otp_release:
  - 17.0
install: mix deps.get
before_install:
  - git clone -b stable git://github.com/elixir-lang/elixir --depth 1
  - make -C elixir
  - export PATH=`pwd`/elixir/bin:$PATH
  - export MIX_ENV=test
  - mix local.hex --force
script: mix test
services:
 - elasticsearch
notifications:
  irc: "irc.freenode.net#funnel"
